---
- name: Diagnostic Ansible AWX
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    file_loc: /home/dhia/Desktop/awxsurvey/survey-template.conf

  tasks:
    - name: Afficher la variable file_loc
      debug:
        var: file_loc

    - name: Créer le dossier si inexistant
      ansible.builtin.file:
        path: /home/dhia/Desktop/awxsurvey
        state: directory
        mode: '0755'

    - name: Créer le template
      template:
        src: survey-template.conf.j2
        dest: "{{ file_loc }}"
