---
- name: Diagnostic Ansible AWX with External Variables
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    serv_name: your_service_name
    option1: value1
    option2: value2
  
  vars_files:
  - /home/dhia/Desktop/awxsurvey/vars.yml
  
  tasks:
    - name: Vérifier la présence des variables
      debug:
        msg: "serv_name={{ serv_name }}, option1={{ option1 }}, option2={{ option2 }}"
